package com.clearsoft.welivre.domain.entities;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.clearsoft.welivre.domain.entities.Feed;
import com.clearsoft.welivre.domain.entities.Plan;
import com.clearsoft.welivre.domain.entities.Follow;

import com.clearsoft.welivre.domain.entities.FeedDao;
import com.clearsoft.welivre.domain.entities.PlanDao;
import com.clearsoft.welivre.domain.entities.FollowDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig feedDaoConfig;
    private final DaoConfig planDaoConfig;
    private final DaoConfig followDaoConfig;

    private final FeedDao feedDao;
    private final PlanDao planDao;
    private final FollowDao followDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        feedDaoConfig = daoConfigMap.get(FeedDao.class).clone();
        feedDaoConfig.initIdentityScope(type);

        planDaoConfig = daoConfigMap.get(PlanDao.class).clone();
        planDaoConfig.initIdentityScope(type);

        followDaoConfig = daoConfigMap.get(FollowDao.class).clone();
        followDaoConfig.initIdentityScope(type);

        feedDao = new FeedDao(feedDaoConfig, this);
        planDao = new PlanDao(planDaoConfig, this);
        followDao = new FollowDao(followDaoConfig, this);

        registerDao(Feed.class, feedDao);
        registerDao(Plan.class, planDao);
        registerDao(Follow.class, followDao);
    }
    
    public void clear() {
        feedDaoConfig.getIdentityScope().clear();
        planDaoConfig.getIdentityScope().clear();
        followDaoConfig.getIdentityScope().clear();
    }

    public FeedDao getFeedDao() {
        return feedDao;
    }

    public PlanDao getPlanDao() {
        return planDao;
    }

    public FollowDao getFollowDao() {
        return followDao;
    }

}
