package com.clearsoft.welivre.domain.entities;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PLAN".
 */
public class Plan {

    private String id;
    private String userId;
    private String quitDate;
    private String motivationsIds;
    private String triggersIds;
    private String cravingsIds;
    private String assistancesIds;
    private String pMotivationPhoto;
    private String pMotivationVideo;
    private String pMotivationAudio;
    private String relapsed;
    private String timestamp;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Plan() {
    }

    public Plan(String id, String userId, String quitDate, String motivationsIds, String triggersIds, String cravingsIds, String assistancesIds, String pMotivationPhoto, String pMotivationVideo, String pMotivationAudio, String relapsed, String timestamp) {
        this.id = id;
        this.userId = userId;
        this.quitDate = quitDate;
        this.motivationsIds = motivationsIds;
        this.triggersIds = triggersIds;
        this.cravingsIds = cravingsIds;
        this.assistancesIds = assistancesIds;
        this.pMotivationPhoto = pMotivationPhoto;
        this.pMotivationVideo = pMotivationVideo;
        this.pMotivationAudio = pMotivationAudio;
        this.relapsed = relapsed;
        this.timestamp = timestamp;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getQuitDate() {
        return quitDate;
    }

    public void setQuitDate(String quitDate) {
        this.quitDate = quitDate;
    }

    public String getMotivationsIds() {
        return motivationsIds;
    }

    public void setMotivationsIds(String motivationsIds) {
        this.motivationsIds = motivationsIds;
    }

    public String getTriggersIds() {
        return triggersIds;
    }

    public void setTriggersIds(String triggersIds) {
        this.triggersIds = triggersIds;
    }

    public String getCravingsIds() {
        return cravingsIds;
    }

    public void setCravingsIds(String cravingsIds) {
        this.cravingsIds = cravingsIds;
    }

    public String getAssistancesIds() {
        return assistancesIds;
    }

    public void setAssistancesIds(String assistancesIds) {
        this.assistancesIds = assistancesIds;
    }

    public String getPMotivationPhoto() {
        return pMotivationPhoto;
    }

    public void setPMotivationPhoto(String pMotivationPhoto) {
        this.pMotivationPhoto = pMotivationPhoto;
    }

    public String getPMotivationVideo() {
        return pMotivationVideo;
    }

    public void setPMotivationVideo(String pMotivationVideo) {
        this.pMotivationVideo = pMotivationVideo;
    }

    public String getPMotivationAudio() {
        return pMotivationAudio;
    }

    public void setPMotivationAudio(String pMotivationAudio) {
        this.pMotivationAudio = pMotivationAudio;
    }

    public String getRelapsed() {
        return relapsed;
    }

    public void setRelapsed(String relapsed) {
        this.relapsed = relapsed;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
